version: '3.3'
services:
  postgres:
    image: postgres:11.6
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ecommerce-postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    links:
      - postgres
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ecommerce-pgadmin:/root/.pgadmin
    networks:
      - postgres
volumes:
  ecommerce-postgres:
  ecommerce-pgadmin:
networks:
  postgres:
    driver: bridge