version: '3.3'
services:
    postgres:
        image: postgres:11.6
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: default
        ports:
            - '5432:5432'
        expose:
            - '5432'
